### PR TITLE
Add store artefact step for rb-service

### PR DESCRIPTION
**Pull request by qvalero**
Then in each service we will want to get report, we will have to add rspec_opts to test.rake file: `--format RspecJunitFormatter --out test-results/rspec/results.xml`
And add in your GemFile the gem `rspec_junit_formatter'` in `group :test`

### CODE REVIEW

**Review by papa-cool — COMMENTED** [review]
Cool!

Why don't you add `store_test_results` step. I will make test result readable in [tests tab](https://app.circleci.com/pipelines/github/jobteaser/crm/543/workflows/de03618d-2386-40e7-992b-363cecafd939/jobs/1146/tests)

Other question, why did you choose html format and not the RspecJunitFormatter used in the monolith? I have no opinion about the format as we can read the result easily.

**Comment by qvalero** [comment]
> Cool!
> 
> Why don't you add `store_test_results` step. I will make test result readable in [tests tab](https://app.circleci.com/pipelines/github/jobteaser/crm/543/workflows/de03618d-2386-40e7-992b-363cecafd939/jobs/1146/tests)
> 
> Other question, why did you choose html format and not the RspecJunitFormatter used in the monolith? I have no opinion about the format as we can read the result easily.

Ah yes let me harmonise. I just needed a way to have access to tests so html was also fine for us, but let's harmonise with monolithe ! I will do the change this afternoon

**Comment by papa-cool** [comment]
You can use both together
`store_test_results` and `store_artifacts`.
the first one make the tests result readable in the tests tab, the second make the artifact available for debugging or anything else.

**Comment by qvalero** [comment]
> You can use both together `store_test_results` and `store_artifacts`.
> The first one make the tests result readable in the tests tab, the second make the artifact available for debugging or anything else.

Yes but if I archive an artefact in xml format it is not really readable, I would have to add another --format and another --out in rspec_opts on service sides. For the moment it is not really "needed" so I will just keep the TEST tab of CircleCi. If we see we have a need to access to scenario through CircleCi we know we have the possibility and we will do the change at this moment.

**Pull request merged**
